server:
  port: 8087
  error:
    include-message: always

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: email-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
