server:
  port: 8081
  error:
    include-message: always

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/adminDb}
  application:
    name: admin-service
  hibernate:
    ddl-auto: update
eureka:
  client:
    serviceurl:
      defaultzone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistery: true
    registerWithEureka: true